---
- name: Create
  hosts: localhost
  connection: local
  vars:
    - target_iam_role: arn:aws:iam::895523100917:role/terraform
    - iam_user_profile: hmpps-token
    - aws_region: eu-west-2
    - overwrite_value: never
  tasks:
    - name: create generate admin password
      set_fact:
        admin_password: "{{ lookup('password', '/dev/null chars=digits,punctuation length=18') }}"
    - name: get creds
      include: ../ansible/ops/aws_credentials.yml
    - name: "Create ssm param entry for AD password"
      include: ../ansible/ops/add_ssm_param.yml
      vars:
        ssm_param_name: "/hmpps/vpn/activeDirectory/admin/password"
        ssm_param_value: "{{ admin_password }}"
        ssm_param_type: "SecureString"
