---
- name: Create VPN Private Key
  hosts: localhost
  connection: local
  vars:
    - target_iam_role: arn:aws:iam::895523100917:role/terraform
    - iam_user_profile: hmpps-token
    - aws_region: eu-west-2
  tasks:
    - name: create openssl private key
      openssl_privatekey:
        path: /tmp/_private_key
        size: 2048
        return_content: yes
      no_log: true
      register: key_file
    - name: get creds
      include: ../ansible/ops/aws_credentials.yml
    - name: "Create ssm param entry for vpn server private key"
      include: ../ansible/ops/add_ssm_param.yml
      vars:
        ssm_param_name: "/hmpps/pki/vpn/server/key"
        ssm_param_value: "{{ key_file.privatekey }}"
        ssm_param_type: "SecureString"
        overwrite_value: never
    - name: Remove generated key file
      file:
        state: absent
        path: "{{ item }}"
      with_items:
        - /tmp/_private_key
        - /tmp/_id_ssh_rsa
